config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :events do
    resources :event_items, only: [:update]
  end

  resources :users, only: :show

  put '/events/:event_id/event_items/:id/unassign' => 'event_items#unassign', as: :event_item_unassign
  get '/items' => 'event_items#index'

  root 'static#home'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_users, :foreign_key => :invited_event_id
  has_many :guests, :through => :event_users
  belongs_to :host, :class_name => "User"
  has_many :event_items, dependent: :destroy
  has_many :items, through: :event_items

  validates :title, :location, :start_time, presence: :true
  validate :end_time_after_start

  def end_time_after_start
    if end_time && end_time <= start_time
      errors.add(:end_time, "End time must be after start time")
    end
  end

  def start_time=(start_time)
    super(Chronic.parse(start_time))
  end

  def start_time
    super
  end

  def end_time=(end_time)
    super(Chronic.parse(end_time))
  end

  def end_time
    super
  end

  def host_name
    host.full_name
  end

  def guests_sorted
    guests.sort_by {|guest| guest.full_name}
  end

  def guest_emails
    guests.sort_by {|guest| guest.email}.map {|guest| guest.email}.join(", ")
  end

  def assigned_items
    event_items.where.not(assigned_person: nil)
  end

  def assigned_items_sorted
    assigned_items.sort_by {|event_item| event_item.item.name}
  end

  def unassigned_items
    event_items.where(assigned_person: nil)
  end

  def unassigned_items_sorted
    unassigned_items.sort_by {|event_item| event_item.item.name}
  end

  def user_items(user)
    self.event_items.where(assigned_person: user)
  end

  def items_attributes=(attributes)
    attributes.values.first[:name].split(",").each do |name_qty|
      name, qty = name_qty.split(":")
      name.titleize.strip!
      qty = 1 if !qty
      qty = qty.to_i
      item = Item.find_or_create_by(name: name)
      qty.times do
        self.items << item
      end
    end
  end

  def guests_attributes=(attributes)
    attributes.values.first[:email].split(",").each do |email|
      email.strip!
      guest = User.find_by(email: email)
      if guest && !self.guests.include?(guest)
        self.guests << guest
      else
        User.invite!(:email => email)
        guest = User.find_by(email: email)
        self.guests << guest if guest && !self.guests.include?(guest)
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  def index
    @hosted_events = current_user.hosted_events
    @invited_events = current_user.invited_events
    @event = Event.new
  end

  def show
    @event = load_event
    authorize @event
    @event_item = @event.event_items.build
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @event }
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = load_event
  end

  def create
    @event = Event.new(host: current_user)
    @event = current_user.hosted_events.build(event_params)
    if @event.save
      flash[:success] = "Your event was successfully created!"
      respond_to do |format|
        format.html { redirect_to event_path(@event) }
        format.json { render json: @event }
      end
    else
      render :new
    end
  end

  def update
    @event = load_event
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event = load_event
    authorize @event
    @event.destroy
    flash[:notice] = "Event deleted"
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(policy(@event).permitted_attributes)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  
  def start_date_helper(event)
    event.start_time.blank? ? "" : format_date(event.start_time)
  end

  def end_date_helper(event)
    event.end_time.blank? ? "n/a" : format_date(event.end_time)
  end

  def format_date(datetime)
    datetime.localtime.strftime("%_m/%-d/%Y at %l:%M%P (%a)")
  end
end

app/views/events/_assigned_item.html.erb
<li><%= assigned_item.item_name %>: <%= assigned_item.assigned_person.full_name %></li>
<%= link_to "Remove", event_item_unassign_path(@event, assigned_item), method: :put if assigned_item.assigned_person == current_user || @event.host == current_user %></li>

app/views/events/_event.html.erb
<div class="col-sm-4 expand-event-index" data-id="<%= event.id %>">
  <div class="panel panel-default">
    <div class="panel-body">                    
      <h4><%= event.title %></h4>
      <p>on <%= start_date_helper(event) %></p>
    </div>
    <div class="panel-footer">
      <div id="event-index-details-<%= event.id %>" style="display: none">
        <p><strong>Location:</strong> <span id="location-<%= event.id %>"></span></p>
        <ul class="list-inline">
          <li><%= link_to "Details", event_path(event), class: "btn btn-sm btn-default" %></li>
          <% if current_user == event.host %>
            <li><%= link_to "Edit", edit_event_path(event), class: "btn btn-sm btn-default" %></li>
            <li><%= link_to "Delete", event_path(event), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-default" %>
          <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/events/_event_simple.html.erb
<h4><span id="event-title"><%= event.title %></span>
  <a class="glyphicon glyphicon-edit btn btn-lg" id="edit-button"></a>
</h4>
<p><strong>Host:</strong> <span id="event-host"><%= event.host_name %></span></p>
<p><strong>Location:</strong> <span id="event-location"><%= event.location %></span></p>
<p><strong>Start Time:</strong> <span id="event-start-time"><%= start_date_helper(event) %></span></p>
<p><strong>End Time:</strong> <span id="event-end-time"><%= end_date_helper(event) %></span></p>

app/views/events/_form.html.erb
<%= bootstrap_form_for @event do |f| %>
  <%= f.text_field :title, label: "Event Title", autofocus: true %>
  <%= f.text_field :location %>
  <%= f.label "Start Time" %>
  <div class="help-block">ex: "8/6/1991 at 1:30pm" OR "next Saturday at noon"</div>
  <%= f.text_field :start_time, value: start_date_helper(@event), hide_label: true %>
  <%= f.text_field :end_time, value: end_date_helper(@event) %>

  <%= f.label "Items Needed" %>
  <%= f.collection_check_boxes :item_ids, Item.sorted, :id, :pretty_name, inline: true, hide_label: true %>

  <%= f.fields_for :items, @event.items.build do |items_fields| %>
    <%= items_fields.label "More Items" %>
    <div class="help-block">Enter more items separated by commas. To add more than one of an item, enter "item:number". For example "wine:4, cheese:2, crackers"</div>
    <%= items_fields.text_field :name, hide_label: true %>
  <% end %>
  
  <%= f.fields_for :guests, [User.new] do |guest_form| %>
    <%= guest_form.label "Guests" %>
    <div class="help-block">Enter guest email addresses separated by commas.</div>
    <%= guest_form.text_area :email, style: "resize:none", rows: "7", cols: "100", hide_label: true, value: @event.guest_emails %>
  <% end %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/events/_guest.html.erb
<li><p><%= guest.full_name %></p></li>

app/views/events/_unassigned_item.html.erb
<div style="display:inline-block; padding-right:5px">
  <a data-id="<%= unassigned_item.id %>" class="btn btn-info btn-sm item-button"><%= unassigned_item.item_name %></a>
</div>

app/views/events/edit.html.erb
<div class="col-sm-12">
  <h1 class="page-header">Edit Event</h1>
</div>
<%= render 'form' %>

app/views/events/index.html.erb
<div class="col-lg-12 col-sm-12">
  <div class="card hovercard">
    <div class="card-background">
      <%= image_tag "streamer.jpg" %>
    </div>
    <div class="card-info">
      <h1 class="card-title">Your Events</h1>
    </div>
  </div>

  <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
    <div class="btn-group" role="group">
      <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <div class="hidden-xs">Hosted</div>
      </button>
    </div>
    <div class="btn-group" role="group">
      <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
        <div class="hidden-xs">Invited</div>
      </button>
    </div>  
  </div>

  <div class="well">
    <div class="tab-content">
      <div class="tab-pane fade in active" id="tab1">
        <% if @hosted_events.size.zero? %>
          <h4>You aren't hosting anything yet. Get a party started by clicking "Show/Hide New Event Form"!</h4>
        <% else %>
          <div class="row" id="hosted-events">
            <%= render @hosted_events %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade in" id="tab2">
        <% if @invited_events.size.zero? %>
          <h4>No upcoming events</h4>
        <% else %>
          <div class="row">
            <%= render @invited_events %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <button class="btn btn-primary" id="show-new-form">Show/Hide New Event Form</button>
</div>

<div class="col-sm-8" id="new-form">
  <h1 class="page-header">New Event</h1>
  <%= render 'form' %>
</div>

<script>
$(function() {
  $(".btn-pref .btn").click(function () {
    $(".btn-pref .btn").removeClass("btn-primary").addClass("btn-default");
    $(this).removeClass("btn-default").addClass("btn-primary");   
  });

  function bindEvent(){
    $(".expand-event-index").click(function(){
      var id = $(this).data("id");
      $('#event-index-details-' + id).toggle(100);
      $.get("/events/" + id + ".json", function(data){
        $('#location-' + id).html(data["event"]["location"]);
      });
    });
  }
  bindEvent();

  $("#show-new-form").click(function(){
    $("#new-form").toggle();
  })

  $("#new_event").submit(function(e){
    $.ajax({
      method: "POST",
      url: "/events",
      data: $(this).serialize(),
      dataType: "json"
    })
      .done(function(data) {
        var template = createEventTemplate(data.event.id, data.event.title, data.event.start_time);
        $("#hosted-events").append(template);
        bindEvent();
        $("#new-form").hide();
      });

    e.preventDefault();
  })

  function createEventTemplate(eventId, title, start){
    return "<div class='col-sm-4 expand-event-index' data-id='" + eventId + "'><div class='panel panel-default'><div class='panel-body'><h4>" + title + "</h4><p>on " + start + "</p></div><div class='panel-footer'><div id='event-index-details-" + eventId + "' style='display: none'><p><strong>Location:</strong> <span id='location-" + eventId + "'></span></p><ul class='list-inline'><li><a class='btn btn-sm btn-default' href='/events/" + eventId + "'>Details</a></li><li><a class='btn btn-sm btn-default' href='/events/" + eventId + "/edit'>Edit</a></li><li><a data-confirm='Are you sure?' class='btn btn-sm btn-default' rel='nofollow' data-method='delete' href='/events/" + eventId + "'>Delete</a></li></ul></div></div></div></div>"
  }

});
</script>

app/views/events/new.html.erb
<div class="col-sm-12">
  <h1 class="page-header">New Event</h1>
</div>
<div class="col-sm-8">
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div id="current-event" data-id="<%= @event.id %>">
  <div class="row">
    <div class="col-sm-3 navigate">
    <a href="#" id="prev-event" class="glyphicon glyphicon-chevron-left btn btn-lg"></a>
    <a href="#" id="next-event" class="glyphicon glyphicon-chevron-right btn btn-lg"></a>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12 bhoechie-tab-container">
      <div class="col-sm-3 bhoechie-tab-menu">
        <div class="list-group">
          <a href="#" class="list-group-item active text-center">
            <h4 class="glyphicon glyphicon-calendar"></h4><br/>Event Details
          </a>
          <a href="#" class="list-group-item text-center">
            <h4 class="glyphicon glyphicon-cutlery"></h4><br/>Who's Bringing What
          </a>
          <a href="#" class="list-group-item text-center">
            <h4 class="glyphicon glyphicon-shopping-cart"></h4><br/>Still Needed
          </a>
          <a href="#" class="list-group-item text-center">
            <h4 class="glyphicon glyphicon-user"></h4><br/>Guests
          </a>
        </div>
      </div>
      <div class="col-sm-9 bhoechie-tab">
        <!-- event details section -->
        <div class="bhoechie-tab-content active">
          <%= render 'event_simple', event: @event %>
        </div>
        <!-- who's bringing what section -->
        <div class="bhoechie-tab-content">
          <div class="items-list">
            <ul id="assigned-items">
              <%= render partial: "assigned_item", collection: @event.assigned_items_sorted %>
            </ul>
          </div>
        </div>
        <!-- still needed section -->
        <div class="bhoechie-tab-content">
          <div id="unassigned-items">
            <%= render partial: "unassigned_item", collection: @event.unassigned_items_sorted %>
          </div>
          <br><br>
          <%= bootstrap_form_for @event do |f| %>
            <%= f.fields_for :items, @event.items.build do |items_fields| %>
              <p>Bringing something not on the list? Enter it here. To add more than one of an item, enter "item:number". For example, "homemade pie:2"</p>
              <%= items_fields.text_field :name, hide_label: true %>
              <% end %>
            <%= f.submit "Add Items", class: "btn btn-primary" %>
          <% end %>
        </div>
        <!-- guests section -->
        <div class="bhoechie-tab-content">
          <div class="guest-list">
            <ol id="guests">
              <%= render partial: "guest", collection: @event.guests_sorted %>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {

    var currentUserId = parseInt($("#current-user").attr("data-id"));
    var eventIds = [];

    $.get("/users/" + currentUserId + ".json", function(data){
      data["user"]["hosted_events"].forEach(function(event){
        eventIds.push(event.id)
      });
      data["user"]["invited_events"].forEach(function(event){
        eventIds.push(event.id)
      });
    });

    function getNextId(currentId){
      var i = eventIds.indexOf(currentId);
      if(i >= 0 && i < eventIds.length - 1){
        var next = eventIds[i + 1];
      } else {
        var next = eventIds[0];
      }
      return next;
    }

    function getPrevId(currentId){
      var i = eventIds.indexOf(currentId);
      if(i == 0){
        var p = eventIds[eventIds.length - 1];
      } else {
        var p = eventIds[i - 1];
      }
      return p;
    }

    var Event = function(id, title, host, location, start, end, event_items, guests) {
      this.id = id,
      this.title = title,
      this.host = host,
      this.location = location,
      this.start = start,
      this.end = end || "n/a",
      this.event_items = event_items
      this.guests = guests
    }
        
    Event.prototype.fullName = function(){
     return this.host.first_name || this.host.email;
    }

    function getEvent(id){
      $.get("/events/" + id + ".json", function(data) {
        var anEvent = new Event(data["event"]["id"], data["event"]["title"], data["event"]["host"], data["event"]["location"], 
          data["event"]["start_time"], data["event"]["end_time"], data["event"]["event_items"], data["event"]["guests"]);
        $('#event-title').text(anEvent.title);
        $('#event-host').text(anEvent.fullName());
        $('#event-location').text(anEvent.location);
        $('#event-start-time').text(anEvent.start);
        $('#event-end-time').text(anEvent.end);

        var assignedItemTemplate = [];
        anEvent.event_items.forEach(function(item){
          if (item.assigned_person != null){
            assignedItemTemplate.push("<li>" + (item.item.name.charAt(0).toUpperCase() + item.item.name.slice(1)) + ": " + (item.assigned_person.first_name || item.assigned_person.email) + "</li>")
          }
        })

        var unassignedItemTemplate = [];
        anEvent.event_items.forEach(function(item){
          if (item.assigned_person == null && item.item != null){
            unassignedItemTemplate.push("<div style='display:inline-block; padding-right:5px'> <a data-id='" + item.id + "' class='btn btn-info btn-sm item-button'>" + (item.item.name.charAt(0).toUpperCase() + item.item.name.slice(1)) + "</a></div>")
          }
        })

        var guestTemplate = [];
        anEvent.guests.forEach(function(guest){
          guestTemplate.push("<li><p>" + (guest.first_name || guest.email) + "</p></li>")
        })

        $('#assigned-items').html(assignedItemTemplate.join(""));
        $('#unassigned-items').html(unassignedItemTemplate.join(""));
        $('#guests').html(guestTemplate.join(""));

        $("#current-event").attr("data-id", anEvent.id);
        bindItemButton();

        if (currentUserId === anEvent.host.id){
          $("#edit-button").show();
        } else {
          $("#edit-button").hide();
        }
      });
    }

    $("#next-event").click(function() {
      var currentId = parseInt($("#current-event").attr("data-id"));
      var nextId = getNextId(currentId);
      getEvent(nextId);
    });

    $("#prev-event").click(function() {
      var currentId = parseInt($("#current-event").attr("data-id"));
      var prevId = getPrevId(currentId);
      getEvent(prevId);
    });

    $("#edit-button").click(function(){
      var currentId = parseInt($("#current-event").attr("data-id"));
      window.location.href = "/events/" + currentId + "/edit"
    });

    function bindItemButton(){
      $(".item-button").click(function(){
        var eventId = parseInt($("#current-event").attr("data-id"));
        var id = $(this).data("id");
        $.ajax({
          method: "PUT",
          url: "/events/" + eventId + "/event_items/" + id
        })
          .done(function() {
            window.location.href = "/events/" + eventId
          });
      })  
    }
    bindItemButton();

    $("div.bhoechie-tab-menu>div.list-group>a").click(function(e) {
      e.preventDefault();
      $(this).siblings('a.active').removeClass("active");
      $(this).addClass("active");
      var index = $(this).index();
      $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
      $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
    });
  });
</script>