config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :events do
    resources :event_items, only: [:update]
  end

  resources :users, only: :show

  put '/events/:event_id/event_items/:id/unassign' => 'event_items#unassign', as: :event_item_unassign
  get '/items' => 'event_items#index'

  root 'static#home'

end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand">BringIt!</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "All Events", events_path %></li>
        <li><%= link_to "New Event", new_event_path %></li>
        <li><%= link_to "All Items", items_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p class="nav navbar-text" id="current-user" data-id="<%= current_user.id %>">Logged in as <%= current_user.full_name %></p>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign In with Facebook", user_omniauth_authorize_path(:facebook) %></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BringIt!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container">

  <%= render 'layouts/navbar' %>
  <%= render 'layouts/messages' %>

  <%= yield %>
</div>
</body>
</html>